"""
EcoShield AI
Risk Analysis Page

This module renders the deterministic cybersecurity risk results
generated by src/risk_engine.py.

Responsibilities:
- Display the final 0-100 security risk score
- Display the Low / Medium / High risk level
- Display risk-category breakdown
- Explain detected risk factors
- Display uncertainties and sanitization requirements
- Provide navigation to the recommendation page
- Allow the user to return to or restart assessment flow

Risk calculation must NOT be implemented in this module.
This page only presents the RiskAssessment already generated
by src/risk_engine.py.
"""

from __future__ import annotations

import streamlit as st

from src.risk_engine import (
    CATEGORY_ACCESSIBILITY,
    CATEGORY_DATA_EXPOSURE,
    CATEGORY_MEDIA_BACKUP,
    CATEGORY_SANITIZATION,
    CATEGORY_TRANSFER,
)

from ui.components import (
    render_empty_state,
    render_notice,
    render_page_header,
    render_risk_badge,
    render_risk_score,
    render_section_header,
    render_spacer,
    render_stat_card,
)

from ui.navigation import (
    PAGE_AI_RECOMMENDATION,
    PAGE_ASSESSMENT,
    PAGE_RISK_ANALYSIS,
    navigate_to,
    force_navigate_to,
    render_protected_page,
)

from ui.state import (
    get_assessment_payload,
    get_recommendation_result,
    get_risk_assessment,
    reset_assessment,
)


# ============================================================
# CATEGORY ORDER
# ============================================================

CATEGORY_ORDER = (
    CATEGORY_DATA_EXPOSURE,
    CATEGORY_SANITIZATION,
    CATEGORY_TRANSFER,
    CATEGORY_ACCESSIBILITY,
    CATEGORY_MEDIA_BACKUP,
)


# ============================================================
# CATEGORY ICONS
# ============================================================

CATEGORY_ICONS = {
    CATEGORY_DATA_EXPOSURE: "🔐",
    CATEGORY_SANITIZATION: "🧹",
    CATEGORY_TRANSFER: "🔄",
    CATEGORY_ACCESSIBILITY: "🛠️",
    CATEGORY_MEDIA_BACKUP: "💾",
}


# ============================================================
# RISK LEVEL MESSAGE
# ============================================================

def _risk_message(
    risk_level: str,
) -> tuple[str, str]:
    """
    Return a semantic title and explanation for the
    calculated risk level.
    """

    normalized = (
        risk_level
        .strip()
        .lower()
    )

    if normalized == "high":

        return (
            "Immediate security preparation is recommended",
            (
                "EcoShield identified significant unresolved "
                "security conditions. Address the highlighted "
                "issues before the device leaves your control."
            ),
        )

    if normalized == "medium":

        return (
            "Security preparation is still required",
            (
                "The device has some unresolved security or "
                "uncertainty factors that should be reviewed "
                "before proceeding with the intended action."
            ),
        )

    return (
        "Device security posture is relatively low risk",
        (
            "EcoShield identified few unresolved security "
            "conditions. Review the remaining recommendations "
            "before proceeding."
        ),
    )


# ============================================================
# ASSESSMENT SUMMARY
# ============================================================

def _render_assessment_summary() -> None:
    """
    Display key device context above the risk analysis.
    """

    payload = (
        get_assessment_payload()
    )

    device_type = (
        payload.get(
            "device_type"
        )
        or "Unknown"
    )

    operating_system = (
        payload.get(
            "operating_system"
        )
        or "Unknown"
    )

    storage_type = (
        payload.get(
            "storage_type"
        )
        or "Unknown"
    )

    disposal_method = (
        payload.get(
            "intended_disposal_method"
        )
        or "Not Decided"
    )

    render_section_header(
        title="Assessment Summary",
        description=(
            "The risk analysis below is based on the device "
            "information supplied in your assessment."
        ),
        icon="🖥️",
    )

    col1, col2, col3, col4 = st.columns(
        4
    )

    with col1:

        render_stat_card(
            label="Device",
            value=device_type,
        )

    with col2:

        render_stat_card(
            label="Operating System",
            value=operating_system,
        )

    with col3:

        render_stat_card(
            label="Storage",
            value=storage_type,
        )

    with col4:

        render_stat_card(
            label="Intended Action",
            value=disposal_method,
        )


# ============================================================
# RISK OVERVIEW
# ============================================================

def _render_risk_overview(
    assessment,
) -> None:
    """
    Display the primary score, risk level, sanitization status,
    and overall risk explanation.
    """

    render_section_header(
        title="Security Risk Overview",
        description=(
            "EcoShield uses deterministic rules to evaluate "
            "the security conditions associated with your "
            "device."
        ),
        icon="🛡️",
    )

    col1, col2 = st.columns(
        [1, 2]
    )

    with col1:

        render_risk_score(
            score=assessment.score,
            risk_level=assessment.risk_level,
        )

        render_spacer(
            "sm"
        )

        render_risk_badge(
            assessment.risk_level
        )

    with col2:

        title, message = (
            _risk_message(
                assessment.risk_level
            )
        )

        normalized = (
            assessment.risk_level
            .strip()
            .lower()
        )

        if normalized == "high":

            notice_type = "error"

        elif normalized == "medium":

            notice_type = "warning"

        else:

            notice_type = "success"

        render_notice(
            title=title,
            message=message,
            notice_type=notice_type,
        )

        render_spacer(
            "sm"
        )

        stat1, stat2 = st.columns(
            2
        )

        with stat1:

            render_stat_card(
                label="Risk Score",
                value=(
                    f"{assessment.score}/100"
                ),
            )

        with stat2:

            render_stat_card(
                label="Sanitization Required",
                value=(
                    "Yes"
                    if assessment.requires_sanitization
                    else "No"
                ),
            )


# ============================================================
# CATEGORY BREAKDOWN
# ============================================================

def _render_category_breakdown(
    assessment,
) -> None:
    """
    Display deterministic category scores.
    """

    render_section_header(
        title="Risk Breakdown",
        description=(
            "These categories explain where EcoShield found "
            "security exposure or unresolved preparation."
        ),
        icon="📊",
    )

    category_scores = (
        assessment.category_scores
    )

    for category in CATEGORY_ORDER:

        score = int(
            category_scores.get(
                category,
                0,
            )
        )

        col1, col2 = st.columns(
            [4, 1]
        )

        with col1:

            icon = (
                CATEGORY_ICONS.get(
                    category,
                    "•",
                )
            )

            st.markdown(
                f"**{icon} {category}**"
            )

            # The deterministic category scores collectively
            # sum to the final 0-100 risk score. This progress
            # indicator therefore shows the contribution of
            # each category to the total risk scale.
            st.progress(
                min(
                    max(
                        score / 100,
                        0.0,
                    ),
                    1.0,
                )
            )

        with col2:

            st.metric(
                "Points",
                score,
            )


# ============================================================
# RISK FACTORS
# ============================================================

def _render_risk_factors(
    assessment,
) -> None:
    """
    Explain every deterministic risk factor returned by
    risk_engine.py.
    """

    render_section_header(
        title="Detected Security Issues",
        description=(
            "Every item below contributed to the calculated "
            "risk score."
        ),
        icon="⚠️",
    )

    factors = (
        assessment.factors
    )

    if not factors:

        render_notice(
            title="No significant risk factors detected",
            message=(
                "The deterministic assessment did not identify "
                "any major cybersecurity risk factor for this "
                "device."
            ),
            notice_type="success",
        )

        return

    for factor in factors:

        with st.expander(
            (
                f"{factor.category} "
                f"• +{factor.points} points"
            ),
            expanded=(
                factor.points >= 10
            ),
        ):

            st.markdown(
                f"**Issue:** {factor.message}"
            )

            st.caption(
                f"Risk factor code: {factor.code}"
            )


# ============================================================
# UNCERTAINTIES
# ============================================================

def _render_uncertainties(
    assessment,
) -> None:
    """
    Display security-relevant uncertain assessment values.
    """

    uncertainties = (
        assessment.uncertainties
    )

    if not uncertainties:
        return

    render_section_header(
        title="Information to Verify",
        description=(
            "Uncertain device information may affect the "
            "confidence of security decisions."
        ),
        icon="❓",
    )

    render_notice(
        title="Some assessment details remain uncertain",
        message=(
            "Verify the items below before transferring, "
            "repairing, recycling, or disposing of the device."
        ),
        notice_type="warning",
    )

    for uncertainty in uncertainties:

        st.markdown(
            f"- {uncertainty}"
        )


# ============================================================
# SANITIZATION STATUS
# ============================================================

def _render_sanitization_status(
    assessment,
) -> None:
    """
    Display whether additional data sanitization is required.
    """

    render_section_header(
        title="Data Sanitization Status",
        description=(
            "Secure removal of residual data is one of the "
            "most important steps before a device leaves "
            "your control."
        ),
        icon="🧹",
    )

    if assessment.requires_sanitization:

        render_notice(
            title="Additional sanitization required",
            message=(
                "EcoShield identified conditions indicating "
                "that further data-removal or device-reset "
                "actions should be completed before proceeding."
            ),
            notice_type="error",
        )

    else:

        render_notice(
            title="No additional sanitization requirement detected",
            message=(
                "Based on the supplied assessment information, "
                "EcoShield did not identify an outstanding "
                "deterministic sanitization requirement."
            ),
            notice_type="success",
        )


# ============================================================
# RECOMMENDATION PREVIEW
# ============================================================

def _render_recommendation_preview() -> None:
    """
    Display a compact recommendation status before navigating
    to the full Recommendation page.
    """

    recommendation = (
        get_recommendation_result()
    )

    if recommendation is None:
        return

    render_section_header(
        title="What Should You Do Next?",
        description=(
            "EcoShield has already generated deterministic "
            "security and sustainability guidance for this "
            "assessment."
        ),
        icon="💡",
    )

    render_notice(
        title=(
            f"Readiness: "
            f"{recommendation.readiness}"
        ),
        message=recommendation.summary,
        notice_type=(
            "error"
            if recommendation.readiness
            == "Not Ready"
            else (
                "warning"
                if recommendation.readiness
                == "Conditional"
                else "success"
            )
        ),
    )


# ============================================================
# PAGE ACTIONS
# ============================================================

def _render_page_actions() -> None:
    """
    Render assessment/recommendation navigation actions.
    """

    st.divider()

    col1, col2 = st.columns(
        2
    )

    with col1:

        reassess_clicked = (
            st.button(
                "← Review Assessment",
                key="risk_review_assessment",
                use_container_width=True,
            )
        )

    with col2:

        recommendation_clicked = (
            st.button(
                "View Recommendation →",
                key="risk_view_recommendation",
                type="primary",
                use_container_width=True,
            )
        )

    if reassess_clicked:

        force_navigate_to(
            PAGE_ASSESSMENT
        )

    if recommendation_clicked:

        navigate_to(
            PAGE_AI_RECOMMENDATION
        )

    render_spacer(
        "sm"
    )

    if st.button(
        "↺ Start a New Assessment",
        key="risk_new_assessment",
    ):

        reset_assessment()

        force_navigate_to(
            PAGE_ASSESSMENT
        )


# ============================================================
# PUBLIC PAGE RENDERER
# ============================================================

def render() -> None:
    """
    Render the complete EcoShield Risk Analysis page.

    app.py discovers this function dynamically.
    """

    # --------------------------------------------------------
    # Protect direct navigation when no assessment exists.
    # --------------------------------------------------------

    if not render_protected_page(
        PAGE_RISK_ANALYSIS
    ):
        return

    assessment = (
        get_risk_assessment()
    )

    if assessment is None:

        render_empty_state(
            title="Risk assessment unavailable",
            description=(
                "EcoShield does not currently have a valid "
                "risk assessment to display."
            ),
            icon="🛡️",
        )

        return

    render_page_header(
        kicker="Deterministic Cybersecurity Assessment",
        title="Risk Analysis",
        subtitle=(
            "Review your device's security risk score, "
            "category breakdown, detected issues, and "
            "remaining preparation requirements."
        ),
        icon="🛡️",
    )

    _render_assessment_summary()

    render_spacer(
        "lg"
    )

    _render_risk_overview(
        assessment
    )

    render_spacer(
        "lg"
    )

    _render_category_breakdown(
        assessment
    )

    render_spacer(
        "lg"
    )

    _render_risk_factors(
        assessment
    )

    render_spacer(
        "lg"
    )

    _render_uncertainties(
        assessment
    )

    render_spacer(
        "lg"
    )

    _render_sanitization_status(
        assessment
    )

    render_spacer(
        "lg"
    )

    _render_recommendation_preview()

    _render_page_actions()